version: '3.1'

services:
  db:
    image: mysql:5.6.43
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"

  flyway_baseline:
    image: boxfuse/flyway:5.2.4
    command: baseline
    volumes:
      - ./conf:/flyway/conf
    depends_on:
      - db

  # flyway_migration:
  #   image: boxfuse/flyway:5.2.4
  #   command: migrate
  #   volumes:
  #     - ./migrations/:/flyway/sql
  #     - ./conf:/flyway/conf
  #   depends_on:
  #     - flyway_baseline
  #   restart: on-failure

  # mysql_dump:
  #   image: mysql:5.6.43
  #   volumes:
  #     - ./dump/:/dump/
  #   command: bash -c "sleep 20 && mysql -h db -uroot -proot --default-character-set=utf8 < <(cat /dump/*.sql)"
  #   depends_on:
  #     - flyway_migration

